import type { Recipe } from "./types";

export const sampleRecipes: Recipe[] = [
  {
    id: "1",
    title: "Garlic Butter Pasta",
    description: "A simple, satisfying pasta tossed in garlic-infused brown butter and fresh parsley.",
    cuisine: "Italian",
    tags: ["pasta", "quick", "vegetarian", "weeknight"],
    ingredients: [
      { amount: "400", unit: "g", name: "spaghetti" },
      { amount: "6", unit: "cloves", name: "garlic, thinly sliced" },
      { amount: "80", unit: "g", name: "unsalted butter" },
      { amount: "1", unit: "handful", name: "fresh parsley, chopped" },
      { amount: "60", unit: "g", name: "parmesan, grated" },
      { amount: "", unit: "", name: "salt and black pepper" },
    ],
    steps: [
      "Bring a large pot of salted water to a boil. Cook spaghetti until al dente, reserving 1 cup pasta water.",
      "While pasta cooks, melt butter in a wide pan over medium heat until it turns golden and nutty.",
      "Add garlic and cook 1–2 minutes until fragrant and lightly golden.",
      "Add drained pasta and a splash of pasta water. Toss vigorously to coat.",
      "Remove from heat, stir in parsley and parmesan. Season and serve.",
    ],
    prepTime: 5,
    cookTime: 15,
    servings: 4,
    createdAt: "2024-01-10T10:00:00Z",
    cooked: 3,
  },
  {
    id: "2",
    title: "Chicken Tikka Masala",
    description: "Tender chicken in a rich, spiced tomato-cream sauce. A weeknight crowd-pleaser.",
    cuisine: "Indian",
    tags: ["chicken", "spiced", "curry", "comfort"],
    ingredients: [
      { amount: "700", unit: "g", name: "chicken thighs, cubed" },
      { amount: "400", unit: "g", name: "canned crushed tomatoes" },
      { amount: "200", unit: "ml", name: "heavy cream" },
      { amount: "1", unit: "large", name: "onion, diced" },
      { amount: "4", unit: "cloves", name: "garlic, minced" },
      { amount: "1", unit: "tbsp", name: "fresh ginger, grated" },
      { amount: "2", unit: "tbsp", name: "tikka masala spice mix" },
      { amount: "1", unit: "tbsp", name: "oil" },
    ],
    steps: [
      "Toss chicken with half the spice mix and a pinch of salt. Set aside 15 minutes.",
      "Heat oil in a heavy pan. Sear chicken in batches until charred. Remove and set aside.",
      "In the same pan, sauté onion until golden. Add garlic, ginger, and remaining spices; cook 2 minutes.",
      "Add tomatoes and simmer 10 minutes. Stir in cream and chicken.",
      "Simmer 15 minutes until sauce thickens. Serve with rice or naan.",
    ],
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    createdAt: "2024-01-15T10:00:00Z",
    cooked: 5,
  },
  {
    id: "3",
    title: "Avocado Toast with Poached Eggs",
    description: "Creamy smashed avocado on sourdough, topped with runny poached eggs.",
    cuisine: "Modern",
    tags: ["breakfast", "eggs", "vegetarian", "quick"],
    ingredients: [
      { amount: "2", unit: "slices", name: "sourdough bread" },
      { amount: "1", unit: "large", name: "ripe avocado" },
      { amount: "2", unit: "", name: "eggs" },
      { amount: "1", unit: "tbsp", name: "white vinegar" },
      { amount: "1/2", unit: "", name: "lemon, juiced" },
      { amount: "", unit: "", name: "chilli flakes, salt, olive oil" },
    ],
    steps: [
      "Toast sourdough until golden and crisp.",
      "Mash avocado with lemon juice, salt, and a drizzle of olive oil.",
      "Bring a pot of water to a gentle simmer. Add vinegar.",
      "Crack each egg into a small cup, swirl the water, and slide eggs in. Poach 3–4 minutes.",
      "Spread avocado on toast, top with eggs, chilli flakes, and cracked pepper.",
    ],
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    createdAt: "2024-02-01T08:00:00Z",
    cooked: 8,
  },
  {
    id: "4",
    title: "Roasted Tomato Soup",
    description: "Deep, sweet roasted tomatoes blended into a velvety soup. Better than any can.",
    cuisine: "European",
    tags: ["soup", "vegetarian", "roasted", "comfort", "weeknight"],
    ingredients: [
      { amount: "1", unit: "kg", name: "ripe tomatoes, halved" },
      { amount: "1", unit: "whole", name: "head of garlic" },
      { amount: "1", unit: "large", name: "onion, quartered" },
      { amount: "3", unit: "tbsp", name: "olive oil" },
      { amount: "500", unit: "ml", name: "vegetable stock" },
      { amount: "1", unit: "tsp", name: "sugar" },
      { amount: "", unit: "", name: "fresh basil, salt, pepper" },
    ],
    steps: [
      "Preheat oven to 200°C. Toss tomatoes, onion, and whole garlic head with olive oil and sugar on a baking tray.",
      "Roast 40 minutes until caramelised and slightly charred at edges.",
      "Squeeze garlic cloves out of their skins. Add all roasted veg to a blender with stock.",
      "Blend until smooth. Pour into a pot and heat through. Season well.",
      "Serve with crusty bread and a drizzle of olive oil.",
    ],
    prepTime: 10,
    cookTime: 45,
    servings: 4,
    createdAt: "2024-02-10T12:00:00Z",
    cooked: 2,
  },
  {
    id: "5",
    title: "Sheet Pan Lemon Herb Salmon",
    description: "Flaky salmon and vegetables roasted together on one pan — effortless and bright.",
    cuisine: "Modern",
    tags: ["fish", "salmon", "healthy", "quick", "weeknight"],
    ingredients: [
      { amount: "4", unit: "fillets", name: "salmon (150g each)" },
      { amount: "300", unit: "g", name: "asparagus, trimmed" },
      { amount: "200", unit: "g", name: "cherry tomatoes" },
      { amount: "1", unit: "", name: "lemon, sliced" },
      { amount: "3", unit: "tbsp", name: "olive oil" },
      { amount: "2", unit: "tbsp", name: "fresh dill or parsley" },
      { amount: "2", unit: "cloves", name: "garlic, minced" },
    ],
    steps: [
      "Preheat oven to 220°C. Line a large baking sheet with parchment.",
      "Toss asparagus and tomatoes with oil, garlic, salt, and pepper. Spread on tray.",
      "Place salmon fillets among the vegetables. Top each with lemon slices and herbs.",
      "Roast 12–15 minutes until salmon is just cooked through and flakes easily.",
      "Squeeze remaining lemon over everything and serve immediately.",
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    createdAt: "2024-03-01T18:00:00Z",
    cooked: 4,
  },
  {
    id: "6",
    title: "Mushroom Risotto",
    description: "Creamy, umami-rich risotto with a mix of wild and cultivated mushrooms.",
    cuisine: "Italian",
    tags: ["rice", "mushroom", "vegetarian", "comfort", "weekend"],
    ingredients: [
      { amount: "300", unit: "g", name: "arborio rice" },
      { amount: "400", unit: "g", name: "mixed mushrooms, sliced" },
      { amount: "1", unit: "litre", name: "warm vegetable stock" },
      { amount: "1", unit: "large", name: "shallot, diced" },
      { amount: "150", unit: "ml", name: "dry white wine" },
      { amount: "60", unit: "g", name: "parmesan, grated" },
      { amount: "30", unit: "g", name: "butter" },
      { amount: "2", unit: "tbsp", name: "olive oil" },
      { amount: "2", unit: "cloves", name: "garlic, minced" },
    ],
    steps: [
      "Heat olive oil in a wide, heavy-bottomed pan. Sauté mushrooms in batches until golden. Set aside.",
      "In the same pan, soften shallot, then add garlic. Add rice and toast 2 minutes.",
      "Pour in wine and stir until absorbed.",
      "Add warm stock one ladle at a time, stirring constantly and waiting for each addition to be absorbed before adding the next. This takes about 20 minutes.",
      "Stir in mushrooms, butter, and parmesan. Rest 2 minutes, season, and serve.",
    ],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    createdAt: "2024-03-15T19:00:00Z",
    cooked: 1,
  },
];
